### ISSUE TITLE
Incorrect month shown

### ISSUE THREAD

**Issue by Dipeshwagle** [getaasciesh/React-Nepali-Calendar#1]
Previous month showed when the calendar initially renders.

**Comment by getaasciesh** [comment]
Will fix that soon bro. You can also create pull requests, if you are able to fix or improvise stuffs.

**Comment by getaasciesh** [comment]
Fixed!!

**Comment by Dipeshwagle** [comment]
Nice work 👍I will surely create PR's if I fix something or improve it. And It would be helpful to others if you update npm package to show GitHub URL and also show readme there .

**Comment by getaasciesh** [comment]
@Dipeshwagle I also updated the npm package

**Comment by Dipeshwagle** [comment]
Looks awesome 🎉

**Comment by Dipeshwagle** [comment]
Updating to 1.1.3 again causes this issue [Link](https://codesandbox.io/s/9y9p449ony). But when I clone this repo and run it locally it works, dug a little but can't seem to find the cause.

**Comment by getaasciesh** [comment]
I might have pushed old bundle 😑

**Comment by getaasciesh** [comment]
Sorry, Published the new version 1.1.4 with actual latest bundle.

**Comment by getaasciesh** [comment]
https://codesandbox.io/s/l2y030r8zm
